name: Documentation

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install doxygen

      - name: Generate docs
        run: |
          cmake -S . -B building_docs
          cmake --build building_docs --target docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
