name: Linux (gcc)

on:
  workflow_run:
    workflows: ["PVS-Studio analysis"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Setup LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Setup dependencies (apt)
        run: |
          sudo apt install libboost-program-options-dev
          sudo ln -sf /usr/bin/clang++-18 /usr/bin/clang++

      - name: Setup dependencies (pip)
        run: |
          sudo pip3 install lit
          sudo pip3 install filecheck

      - name: Configure
        run: cmake -S . -B build
        shell: bash
        env:
          CC: gcc-13
          CXX: g++-13
      
      - name: Build
        run: cmake --build build -j 16

      - name: Test
        run: |
          sudo cmake --build build --target check-all
      
      - name: Install
        run: |
          sudo cmake --build build --target install