name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build & test & install"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM repo
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Install dependencies (apt)
        run: |
          sudo apt install libboost-program-options-dev clang-18
          sudo ln -sf /usr/bin/clang++-18 /usr/bin/clang++

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Install dependencies (pip)
        run: |
          sudo pip3 install lit
          sudo pip3 install filecheck

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j 4

      - name: Test
        run: |
          sudo cmake --build build --target check-all

      - name: Install
        run: |
          sudo cmake --build build --target install
